# Generated by Django 3.2.5 on 2021-07-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['poke_api_id'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['poke_api_id'],
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('height', models.SmallIntegerField()),
                ('weight', models.SmallIntegerField()),
                ('small_image_url', models.URLField()),
                ('large_image_url', models.URLField()),
                ('moves', models.ManyToManyField(to='api.Move')),
                ('types', models.ManyToManyField(to='api.Type')),
            ],
            options={
                'ordering': ['poke_api_id'],
            },
        ),
    ]
